### ISSUE TITLE
Can't launch this addon when there is no chanel

### ISSUE THREAD

**Issue by Astaoth** [webmeister/plugin.video.youtube.channels#1]
Hi !

Thank you for sharing the link of this addon from the repo of the main youtube addon.

I try to use it, but it appears this addon can't be started if there is no saved youtube channel.

In the kodi logfile, I have : 
```
2020-02-25 18:47:43.104 T:2070921424   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: search() takes exactly 1 argument (0 given)
                                            Traceback (most recent call last):
                                              File "/home/jack/.kodi/addons/plugin.video.youtube.channels/default.py", line 353, in <module>
                                                locals()[target](**args)
                                              File "/home/jack/.kodi/addons/plugin.video.youtube.channels/default.py", line 161, in myChannels
                                                search()
                                            TypeError: search() takes exactly 1 argument (0 given)
                                            -->End of Python script error report<--
2020-02-25 18:47:43.358 T:2096099536   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube.channels/
2020-02-25 18:47:43.367 T:2973232224   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube.channels/) failed
```

After a quick look in the source code, this addon first try to open the file ~/.kodi/userdata/addon_data/plugin.video.youtube.channels/youtube.channels, which doesn't exist the first time I start this plugin. If there is no loaded chans from this file, this plugin start a function with no parameter, but python complains about it. 

Is it possible to have the youtube.channels file generated if it doesn't exist ?

**Comment by webmeister** [comment]
Thanks for reporting, this happens when the code has only a single user ;) Has been fixed now.
