### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by s0rau** [webmeister/plugin.video.youtube.channels#9]
Optimization :
1/ I've to wait about ± 1minute before video opened and can stream it.
In plugin.video.youtube.channels 6.6.0 it takes several seconds.

2/ Some characters seems not to be supported éèêà.. on search

**Comment by Milliw** [comment]
Did just a quick test and it started one video within a couple of seconds. Maybe you´re using a slow device?

**Comment by s0rau** [comment]
I'm using RPI1 for the test but i'm using the same rpi1 to test plugin.video.youtube 6.6.0 it takes several seconds before openning videos.

**Comment by s0rau** [comment]
logs for 29 minutes video stream  we can see 20:22 to 20:24 :


2020-03-02 20:21:03.330 T:1937375248   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2020-03-02 20:21:18.102 T:1560413056  NOTICE: script.module.youtube.dl: youtube_dl core version: 2019.09.12.1
2020-03-02 20:22:34.985 T:1510929280  NOTICE: Previous line repeats 2 times.
2020-03-02 20:22:34.990 T:1510929280 WARNING: addons must not activate DialogBusy
2020-03-02 20:24:31.095 T:1510929280   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'streamURL'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube.channels/default.py", line 356, in <module>
                                                locals()[target](**args)
                                              File "/storage/.kodi/addons/plugin.video.youtube.channels/default.py", line 269, in playVideo
                                                listitem = xbmcgui.ListItem(path=getYoutubeUrl(url))
                                              File "/storage/.kodi/addons/plugin.video.youtube.channels/default.py", line 100, in getYoutubeUrl
                                                return YDStreamExtractor.getVideoInfo('http://www.youtube.com/watch?v=' + youtubeID, quality=2).streamURL()
                                            AttributeError: 'NoneType' object has no attribute 'streamURL'
                                            -->End of Python script error report<--
2020-03-02 20:24:32.898 T:1937375248   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube.channels/?url=7NtSwTuai08&target=playVideo]

**Comment by s0rau** [comment]
Another test a 21 minutes video :

2020-03-02 20:26:41.850 T:1510929280  NOTICE: script.module.youtube.dl: youtube_dl core version: 2019.09.12.1
2020-03-02 20:26:42.086 T:1510929280 WARNING: addons must not activate DialogBusy
2020-03-02 20:28:37.495 T:1937375248  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.youtube.channels/?url=J4RN2j3KY2o&target=playVideo
2020-03-02 20:28:38.507 T:1578361728  NOTICE: Creating InputStream
2020-03-02 20:28:40.745 T:1578361728  NOTICE: Creating Demuxer
2020-03-02 20:28:45.723 T:1578361728  NOTICE: Opening stream: 0 source: 256
2020-03-02 20:28:45.868 T:1578361728  NOTICE: Creating video thread
2020-03-02 20:28:46.794 T:1578361728  NOTICE: Opening stream: 1 source: 256
2020-03-02 20:28:46.802 T:1578361728  NOTICE: Creating audio thread
2020-03-02 20:28:47.275 T:1578361728  NOTICE: OMXClock using audio as reference
